### ISSUE TITLE
support Compose-JB?

### ISSUE THREAD

**Issue by ElisaMin** [Kyant0/Monet#1]

**Comment by Kyant0** [comment]
This library was planned to be multiplatform, but I had no idea how to support both Kotlin multiplatform (common, or Compose JB) and Android, so it's Android only now.
If you know how to do it, welcome to tell me or PR.

**Comment by ElisaMin** [comment]
好 我试试看

**Comment by Kyant0** [comment]
Good job, thanks for your efforts. 😉
