### ISSUE TITLE
[feature request] ImageBitmap.getKeyColors(k: Int): List<Color> in ComposeMonet

### ISSUE THREAD

**Issue by FunnySaltyFish** [Kyant0/Monet#4]
hey, I want to use the library to support dynamic theme. I've tried ComposeMonet and it worked perfect on my phone. However, it caused crash on some users' phones when testing. So I turn my eyes back and find that there is no `ImageBitmap.getKeyColors(k: Int): List<Color>` function here. Could you please add it as well?

**Comment by FunnySaltyFish** [comment]
ps: I've tried [androidx.palette](https://developer.android.google.cn/jetpack/androidx/releases/palette) but it works not as well as this. Sometimes its result is very bad. So hope you can add it.

**Comment by Kyant0** [comment]
Sorry for the inconvenience. This library is different from the rust version library, so there is not the function you said. But the result of the rust version is not perfect somehow.

**Comment by Kyant0** [comment]
Are you using the rust version?

**Comment by FunnySaltyFish** [comment]
我试过那个 aar 文件，在测试时导致了一台Android11的魅族手机崩溃，所以想试试Kotlin版本的，发现这里缺失了"getKeyColors"。Rust那个版本应该也是你写的？能在Kotlin版本这里加上这个函数吗？或者能解决Rust版本的崩溃问题吗？

**Comment by FunnySaltyFish** [comment]
我发现在 Android 12 以下的设备，使用就崩溃（无论是 Monet 还是 ComposeMonet），这个库必须要 Android 12及以上吗？

**Comment by FunnySaltyFish** [comment]
崩溃日志：
```
OS Version：9_28
Vendor: Xiaomi
Model: Redmi 6
Exception: Resource ID #0x1060028
android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:221)
android.content.res.MiuiResourcesImpl.getValue(MiuiResourcesImpl.java:96)
android.content.res.Resources.getColor(Resources.java:975)
androidx.compose.material3.ColorResourceHelper.getColor-WaAFU9c(DynamicTonalPalette.kt:186)
androidx.compose.material3.DynamicTonalPaletteKt.dynamicTonalPalette(DynamicTonalPalette.kt:41)
androidx.compose.material3.DynamicTonalPaletteKt.dynamicLightColorScheme(DynamicTonalPalette.kt:117)
com.funny.translation.theme.ThemeKt.TransTheme(Theme.kt:163)
...
```

**Comment by FunnySaltyFish** [comment]
I found the reason why it crashed, which was my fault. Sorry to disturb.
